title: みむねこのーと
description: 
baseurl: "/classroom" # the subpath of your site, e.g. /blog
url: "https://mimneko.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: assets
  style: compressed
